# Bonnibel project configuration
name = "libc"
default-config = "configs/release.toml"
custom-rules = "configs/custom.ninja"

[variables]
warnflags = [
	"-Wformat=2", "-Winit-self", "-Wfloat-equal", "-Winline",
	"-Wmissing-format-attribute", "-Wmissing-include-dirs", "-Wswitch",
	"-Wdisabled-optimization", "-Wpointer-arith", "-Wno-attributes",
	"-Wno-sign-compare", "-Wno-multichar", "-Wno-div-by-zero",
	"-Wno-endif-labels", "-Wno-pragmas", "-Wno-format-extra-args",
	"-Wno-unused-result", "-Wno-deprecated-declarations",
	"-Wno-unused-function", "-Wno-address-of-packed-member",
	"-Wno-invalid-offsetof", "-Werror",
]

ccflags = [
    "-fcolor-diagnostics",
    "-DVERSION_MAJOR=${version_major}",
    "-DVERSION_MINOR=${version_minor}",
    "-DVERSION_PATCH=${version_patch}",
    "-DVERSION_GITSHA=0x${version_sha}",
    '-DGIT_VERSION=\"${version_major}.${version_minor}.${version_patch}+${version_sha}\"',
    "${warnflags}",
]

asflags = [
    "-DVERSION_MAJOR=${version_major}",
    "-DVERSION_MINOR=${version_minor}",
    "-DVERSION_PATCH=${version_patch}",
    "-DVERSION_GITSHA=0x${version_sha}",
]

cflags = "-std=c11"

