# Bonnibel module

name = "libc"
kind = "lib"
output = "libc.a"
targets = [ "user" ]
includes = [ "src/libc/include", "src/pdclib/include" ]
default = true

sources = [
    "functions/_dlmalloc/malloc.c",
    "functions/_PDCLIB/_PDCLIB_flushbuffer.c",
    "functions/_PDCLIB/_PDCLIB_Exit.c",
    "functions/_PDCLIB/_PDCLIB_remove.c",
    "functions/_PDCLIB/_PDCLIB_rename.c",
    "functions/_PDCLIB/_PDCLIB_seek.c",
    "functions/_PDCLIB/_PDCLIB_fillbuffer.c",
    "functions/_PDCLIB/_PDCLIB_stdinit.c",
    "functions/_PDCLIB/_PDCLIB_open.c",
    "functions/_PDCLIB/_PDCLIB_close.c",
    "functions/time/clock.c",
    "functions/time/timespec_get.c",
    "functions/time/time.c",
    "functions/stdio/remove.c",
    "functions/stdio/tmpfile.c",
    "functions/threads/thrd_sleep.c",
    "functions/threads/thrd_current.c",
    "functions/threads/cnd_init.c",
    "functions/threads/mtx_unlock.c",
    "functions/threads/thrd_exit.c",
    "functions/threads/cnd_broadcast.c",
    "functions/threads/mtx_init.c",
    "functions/threads/thrd_equal.c",
    "functions/threads/cnd_signal.c",
    "functions/threads/mtx_trylock.c",
    "functions/threads/tss_set.c",
    "functions/threads/call_once.c",
    "functions/threads/cnd_destroy.c",
    "functions/threads/thrd_create.c",
    "functions/threads/tss_create.c",
    "functions/threads/mtx_destroy.c",
    "functions/threads/tss_delete.c",
    "functions/threads/tss_get.c",
    "functions/threads/thrd_yield.c",
    "functions/threads/mtx_timedlock.c",
    "functions/threads/thrd_join.c",
    "functions/threads/mtx_lock.c",
    "functions/threads/cnd_timedwait.c",
    "functions/threads/cnd_wait.c",
    "functions/threads/thrd_detach.c",
    "functions/stdlib/getenv_s.c",
    "functions/stdlib/getenv.c",
    "functions/stdlib/system.c",
    "functions/signal/signal.c",
    "functions/signal/raise.c",

    "../pdclib/functions/_PDCLIB/_PDCLIB_strtox_prelim.c",
    "../pdclib/functions/_PDCLIB/_PDCLIB_is_leap.c",
    "../pdclib/functions/_PDCLIB/_PDCLIB_load_lc_monetary.c",
    "../pdclib/functions/_PDCLIB/_PDCLIB_load_lines.c",
    "../pdclib/functions/_PDCLIB/_PDCLIB_bigint_log2.c",
    "../pdclib/functions/_PDCLIB/_PDCLIB_prepwrite.c",
    "../pdclib/functions/_PDCLIB/_PDCLIB_strtox_main.c",
    "../pdclib/functions/_PDCLIB/_PDCLIB_load_lc_collate.c",
    "../pdclib/functions/_PDCLIB/_PDCLIB_bigint.c",
    "../pdclib/functions/_PDCLIB/_PDCLIB_bigint10.c",
    "../pdclib/functions/_PDCLIB/_PDCLIB_load_lc_numeric.c",
    "../pdclib/functions/_PDCLIB/_PDCLIB_bigint_tostring.c",
    "../pdclib/functions/_PDCLIB/_PDCLIB_seed.c",
    "../pdclib/functions/_PDCLIB/assert.c",
    "../pdclib/functions/_PDCLIB/_PDCLIB_bigint2.c",
    "../pdclib/functions/_PDCLIB/_PDCLIB_bigint_add.c",
    "../pdclib/functions/_PDCLIB/_PDCLIB_load_lc_messages.c",
    "../pdclib/functions/_PDCLIB/_PDCLIB_closeall.c",
    "../pdclib/functions/_PDCLIB/_PDCLIB_digits.c",
    "../pdclib/functions/_PDCLIB/_PDCLIB_bigint32.c",
    "../pdclib/functions/_PDCLIB/_PDCLIB_print.c",
    "../pdclib/functions/_PDCLIB/_PDCLIB_filemode.c",
    "../pdclib/functions/_PDCLIB/_PDCLIB_bigint_shl.c",
    "../pdclib/functions/_PDCLIB/_PDCLIB_scan.c",
    "../pdclib/functions/_PDCLIB/errno.c",
    "../pdclib/functions/_PDCLIB/_PDCLIB_bigint_mul_dig.c",
    "../pdclib/functions/_PDCLIB/stdarg.c",
    "../pdclib/functions/_PDCLIB/_PDCLIB_bigint_div_dig.c",
    "../pdclib/functions/_PDCLIB/_PDCLIB_strtok.c",
    "../pdclib/functions/_PDCLIB/_PDCLIB_bigint64.c",
    "../pdclib/functions/_PDCLIB/_PDCLIB_bigint_sub.c",
    "../pdclib/functions/_PDCLIB/_PDCLIB_bigint_cmp.c",
    "../pdclib/functions/_PDCLIB/_PDCLIB_bigint_mul.c",
    "../pdclib/functions/_PDCLIB/_PDCLIB_load_lc_time.c",
    "../pdclib/functions/_PDCLIB/_PDCLIB_prepread.c",
    "../pdclib/functions/_PDCLIB/_PDCLIB_load_lc_ctype.c",
    "../pdclib/functions/_PDCLIB/_PDCLIB_isstream.c",
    "../pdclib/functions/_PDCLIB/_PDCLIB_atomax.c",
    "../pdclib/functions/_PDCLIB/_PDCLIB_getstream.c",
    "../pdclib/functions/_PDCLIB/_PDCLIB_init_file_t.c",
    "../pdclib/functions/time/gmtime_s.c",
    "../pdclib/functions/time/gmtime.c",
    "../pdclib/functions/time/ctime_s.c",
    "../pdclib/functions/time/asctime_s.c",
    "../pdclib/functions/time/localtime_s.c",
    "../pdclib/functions/time/localtime.c",
    "../pdclib/functions/time/ctime.c",
    "../pdclib/functions/time/asctime.c",
    "../pdclib/functions/time/strftime.c",
    "../pdclib/functions/time/difftime.c",
    "../pdclib/functions/time/mktime.c",
    "../pdclib/functions/stdio/fgetpos.c",
    "../pdclib/functions/stdio/printf.c",
    "../pdclib/functions/stdio/vfprintf.c",
    "../pdclib/functions/stdio/scanf.c",
    "../pdclib/functions/stdio/freopen.c",
    "../pdclib/functions/stdio/puts.c",
    "../pdclib/functions/stdio/ftell.c",
    "../pdclib/functions/stdio/vsnprintf.c",
    "../pdclib/functions/stdio/vprintf.c",
    "../pdclib/functions/stdio/freopen_s.c",
    "../pdclib/functions/stdio/fprintf.c",
    "../pdclib/functions/stdio/fopen.c",
    "../pdclib/functions/stdio/vfscanf.c",
    "../pdclib/functions/stdio/putchar.c",
    "../pdclib/functions/stdio/setvbuf.c",
    "../pdclib/functions/stdio/tmpnam.c",
    "../pdclib/functions/stdio/snprintf.c",
    "../pdclib/functions/stdio/vscanf.c",
    "../pdclib/functions/stdio/rename.c",
    "../pdclib/functions/stdio/vsscanf.c",
    "../pdclib/functions/stdio/getchar.c",
    "../pdclib/functions/stdio/fsetpos.c",
    "../pdclib/functions/stdio/fgetc.c",
    "../pdclib/functions/stdio/clearerr.c",
    "../pdclib/functions/stdio/rewind.c",
    "../pdclib/functions/stdio/getc.c",
    "../pdclib/functions/stdio/feof.c",
    "../pdclib/functions/stdio/fputc.c",
    "../pdclib/functions/stdio/tmpfile_s.c",
    "../pdclib/functions/stdio/fseek.c",
    "../pdclib/functions/stdio/ferror.c",
    "../pdclib/functions/stdio/fopen_s.c",
    "../pdclib/functions/stdio/vsprintf.c",
    "../pdclib/functions/stdio/perror.c",
    "../pdclib/functions/stdio/ungetc.c",
    "../pdclib/functions/stdio/fclose.c",
    "../pdclib/functions/stdio/setbuf.c",
    "../pdclib/functions/stdio/fputs.c",
    "../pdclib/functions/stdio/fwrite.c",
    "../pdclib/functions/stdio/putc.c",
    "../pdclib/functions/stdio/fscanf.c",
    "../pdclib/functions/stdio/fflush.c",
    "../pdclib/functions/stdio/sscanf.c",
    "../pdclib/functions/stdio/sprintf.c",
    "../pdclib/functions/stdio/fgets.c",
    "../pdclib/functions/stdio/fread.c",
    "../pdclib/functions/inttypes/imaxdiv.c",
    "../pdclib/functions/inttypes/imaxabs.c",
    "../pdclib/functions/inttypes/strtoimax.c",
    "../pdclib/functions/inttypes/strtoumax.c",
    "../pdclib/functions/string/memcmp.c",
    "../pdclib/functions/string/memmove_s.c",
    "../pdclib/functions/string/strncat.c",
    "../pdclib/functions/string/strcat_s.c",
    "../pdclib/functions/string/memchr.c",
    "../pdclib/functions/string/strrchr.c",
    "../pdclib/functions/string/memcpy.c",
    "../pdclib/functions/string/strcmp.c",
    "../pdclib/functions/string/strlen.c",
    "../pdclib/functions/string/strncpy_s.c",
    "../pdclib/functions/string/memmove.c",
    "../pdclib/functions/string/strcpy_s.c",
    "../pdclib/functions/string/strxfrm.c",
    "../pdclib/functions/string/strtok.c",
    "../pdclib/functions/string/memcpy_s.c",
    "../pdclib/functions/string/memset_s.c",
    "../pdclib/functions/string/strspn.c",
    "../pdclib/functions/string/strcpy.c",
    "../pdclib/functions/string/strchr.c",
    "../pdclib/functions/string/strncat_s.c",
    "../pdclib/functions/string/strcoll.c",
    "../pdclib/functions/string/strncmp.c",
    "../pdclib/functions/string/strpbrk.c",
    "../pdclib/functions/string/strerror_s.c",
    "../pdclib/functions/string/strcspn.c",
    "../pdclib/functions/string/strstr.c",
    "../pdclib/functions/string/strcat.c",
    "../pdclib/functions/string/strtok_s.c",
    "../pdclib/functions/string/strncpy.c",
    "../pdclib/functions/string/strerrorlen_s.c",
    "../pdclib/functions/string/strerror.c",
    "../pdclib/functions/string/memset.c",
    "../pdclib/functions/_tzcode/_PDCLIB_tzset_unlocked.c",
    "../pdclib/functions/_tzcode/_PDCLIB_increment_overflow.c",
    "../pdclib/functions/_tzcode/_PDCLIB_mktime_tzname.c",
    "../pdclib/functions/_tzcode/_PDCLIB_timesub.c",
    "../pdclib/functions/_tzcode/_PDCLIB_update_tzname_etc.c",
    "../pdclib/functions/_tzcode/_PDCLIB_init_ttinfo.c",
    "../pdclib/functions/_tzcode/_PDCLIB_tzload.c",
    "../pdclib/functions/_tzcode/_PDCLIB_tzparse.c",
    "../pdclib/functions/_tzcode/_PDCLIB_gmtsub.c",
    "../pdclib/functions/_tzcode/_PDCLIB_localsub.c",
    "../pdclib/functions/_tzcode/_PDCLIB_localtime_tzset.c",
    "../pdclib/functions/_tzcode/_PDCLIB_gmtcheck.c",
    "../pdclib/functions/ctype/isspace.c",
    "../pdclib/functions/ctype/isupper.c",
    "../pdclib/functions/ctype/tolower.c",
    "../pdclib/functions/ctype/isalnum.c",
    "../pdclib/functions/ctype/isdigit.c",
    "../pdclib/functions/ctype/isblank.c",
    "../pdclib/functions/ctype/isprint.c",
    "../pdclib/functions/ctype/isgraph.c",
    "../pdclib/functions/ctype/islower.c",
    "../pdclib/functions/ctype/iscntrl.c",
    "../pdclib/functions/ctype/isalpha.c",
    "../pdclib/functions/ctype/ispunct.c",
    "../pdclib/functions/ctype/toupper.c",
    "../pdclib/functions/ctype/isxdigit.c",
    "../pdclib/functions/stdlib/atoll.c",
    "../pdclib/functions/stdlib/abort_handler_s.c",
    "../pdclib/functions/stdlib/abort.c",
    "../pdclib/functions/stdlib/quick_exit.c",
    "../pdclib/functions/stdlib/llabs.c",
    "../pdclib/functions/stdlib/exit.c",
    "../pdclib/functions/stdlib/labs.c",
    "../pdclib/functions/stdlib/ignore_handler_s.c",
    "../pdclib/functions/stdlib/bsearch.c",
    "../pdclib/functions/stdlib/_Exit.c",
    "../pdclib/functions/stdlib/strtoll.c",
    "../pdclib/functions/stdlib/strtol.c",
    "../pdclib/functions/stdlib/atoi.c",
    "../pdclib/functions/stdlib/strtoull.c",
    "../pdclib/functions/stdlib/div.c",
    "../pdclib/functions/stdlib/strtoul.c",
    "../pdclib/functions/stdlib/qsort_s.c",
    "../pdclib/functions/stdlib/qsort.c",
    "../pdclib/functions/stdlib/atexit.c",
    "../pdclib/functions/stdlib/at_quick_exit.c",
    "../pdclib/functions/stdlib/lldiv.c",
    "../pdclib/functions/stdlib/srand.c",
    "../pdclib/functions/stdlib/set_constraint_handler_s.c",
    "../pdclib/functions/stdlib/bsearch_s.c",
    "../pdclib/functions/stdlib/atol.c",
    "../pdclib/functions/stdlib/rand.c",
    "../pdclib/functions/stdlib/abs.c",
    "../pdclib/functions/stdlib/ldiv.c",
    "../pdclib/functions/locale/setlocale.c",
    "../pdclib/functions/locale/localeconv.c",
]

[variables]
ccflags = [
    "${ccflags}",
	"-DLACKS_UNISTD_H",
	"-DLACKS_FCNTL_H",
	"-DLACKS_SYS_PARAM_H",
	"-DLACKS_SYS_MMAN_H",
	"-DLACKS_STRINGS_H",
	"-DLACKS_SYS_TYPES_H",
	"-DLACKS_SCHED_H",
	"-DHAVE_MMAP=0",
	"-I${source_root}/src/include",
]
