[targets.user]
cc = "clang"
cxx = "clang++"
ld = "ld.lld"
ar = "ar"
nasm = "nasm"
objcopy = "objcopy"

ccflags = [
    "-nostdlib",
    "-nostdinc",
    "-ffreestanding",
    "-nodefaultlibs",
    "-fno-omit-frame-pointer",
	"-g", "-ggdb",
	"${ccflags}",
]

ldflags = [
    "-nostdlib",
    "-Bstatic",
	"-z", "separate-code",
	"${ldflags}",
]
